language: python
python:
  - "3.6"
dist: trusty
sudo: required

install:
  # command to install dependencies
  - pip install --upgrade wheel setuptools pip
  - pip install -r requirements/development.txt
script:
  - mkdir -p build && cd build
  - cmake ..
  - make
  - ctest --verbose
  - pip install -e .
  - zolware -v
  - py.test --cov=zolware tests/
  - python setup.py test
after_success:
   - codecov --file coverage/lcov.info --disable search
